### ISSUE TITLE
Pimple 3.2.x support

### ISSUE THREAD

**Issue by mantis** [cnam/security-jwt-service-provider#28]
It looks like the composer.json needs to be updated to support the current versions of pimple being pushed out: 

- Installation request for cnam/security-jwt-service-provider ^2.1 -> satisfiable by cnam/security-jwt-service-provider[2.1.1]
- cnam/security-jwt-service-provider 2.1.1 requires pimple/pimple 3.0.* -> no matching package found.

**Comment by anibalsanchez** [comment]
+1

I've just implemented it without the pimple 3.0 restriction and it works perfectly well.

**Comment by tsantos84** [comment]
I'm getting this error requiring `cnam/security-jwt-service-provider:2.1.1`

```
  Problem 1
    - Installation request for cnam/security-jwt-service-provider ~2.1.1 -> satisfiable by cnam/security-jwt-service-provider[2.1.1].
    - Conclusion: remove pimple/pimple v3.2.2
    - Conclusion: don't install pimple/pimple v3.2.2
    - cnam/security-jwt-service-provider 2.1.1 requires pimple/pimple 3.0.* -> satisfiable by pimple/pimple[v3.0.0, v3.0.1, v3.0.2].
    - Can only install one of: pimple/pimple[v3.0.0, v3.2.2].
    - Can only install one of: pimple/pimple[v3.0.1, v3.2.2].
    - Can only install one of: pimple/pimple[v3.0.2, v3.2.2].
    - Installation request for pimple/pimple (locked at v3.2.2) -> satisfiable by pimple/pimple[v3.2.2].
```

I think still having problem with pimple 3.2.
